### ISSUE TITLE
Union declaration shows as syntax error.

### ISSUE THREAD

**Issue by dgriffith0** [tomwyr/union#3]
Undefined name 'Union' used as an annotation.
Try defining the name or importing it from another library.

**Comment by yoodame** [comment]
Yea the `import 'package:union/union.dart';` doesn't exist. Is `union` reserved? 

@tomwyr

**Comment by dgriffith0** [comment]
This error occurs if I dont specify the version.

Because every version of union_generator from git depends on union from git https://github.com/tomwyr/union.git at v1.0.0 in union and crescent_asset depends on union from git https://github.com/tomwyr/union.git at HEAD in union, union_generator from git is forbidden.
So, because crescent_asset depends on union_generator from git, version solving failed.

**Comment by tomwyr** [comment]
I started pushing tags for package versioning. Add `ref` with a specific version to the pubspec file:
```yaml
dependencies:
  union:
    git:
      url: https://github.com/tomwyr/union.git
      path: union
      ref: v1.0.0
```
